# fly.toml app configuration file generated for tatarin on 2025-12-27T22:00:57+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tatarin'
primary_region = 'fra'

[build]

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "data"
  destination = "/data"
